#!/bin/bash

firstrun() {
	echo "First run"
	cp -r /var/lib/mysql/* /data
	chown -R mysql /data
	chown root /data/debian*


	#echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_PASS';" >> firstrun.sql
	#echo "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASS';" >> firstrun.sql
	#echo "GRANT ALL on *.* to '$MYSQL_USER'@'%' WITH GRANT OPTION;" >> firstrun.sql

	#mysql -h localhost -uroot -proot < firstrun.sql

	#ON_CREATE_DB, MYSQL_PASS, MYSQL_USER

	echo "[galera]" >> /etc/mysql/conf.d/galera.cnf
	echo "wsrep_sst_auth=$CLUSTER_AUTH" >> /etc/mysql/conf.d/galera.cnf
	echo "wsrep_cluster_name=$CLUSTER_NAME" >> /etc/mysql/conf.d/galera.cnf



	#echo "gcache.dir = /data/" >> /etc/mysql/my.cnf
	#echo "gcache.name = /data/galera.cache"  >> /etc/mysql/my.cnf

}

main() {
	if [[ ! -f /data/debian-10.0.flag ]]
	then
		firstrun
	fi

	case "$1" in
		master)
			echo "Starting master"
			/usr/bin/mysqld_safe --wsrep_cluster_address=gcomm:// --wsrep-new-cluster
			;;
		node)
			echo "Starting node"
			if [[ -z "$2" ]]
			then
				echo "Missing master node IP"
			else
				/usr/bin/mysqld_safe --wsrep_cluster_address=gcomm://$2
			fi
			;;
		*)
			echo "start <master|node> <master node ip>"
	esac
}

main $@

